apiVersion: v1
kind: Template
objects:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: parksmap${PIPELINE_NAME_SUFFIX}-pipeline
  spec:
    runPolicy: SerialLatestOnly
    source:
      git:
        uri: "https://github.com/ajdelaguila/openshift-parksmap.git"
      type: Git
    strategy:
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    triggers:
      - type: "GitHub"
        github:
          secret: "${GITHUB_SECRET}"
parameters:
  - name: PIPELINE_NAME_SUFFIX
    displayName: Pipeline's name suffix.
    required: false
  - name: GITHUB_SECRET
    displayName: Secret for GitHub trigger
    generate: expression
    from: "[a-zA-Z0-9]{12}"
